# Generated by Django 5.1.3 on 2024-12-16 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_customuser_groups_remove_customuser_roles_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/videos/'),
        ),
    ]
