# Generated by Django 5.1.3 on 2024-12-26 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_movie_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to='movie/previews/'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='movie/videos/'),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
